name: Library
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Check Code Formatting
        run: yarn prettier packages/field-plugin --check
      - name: Check Types
        run: yarn workspace @storyblok/field-plugin check:types
      - name: Lint
        run: |
          yarn eslint packages/field-plugin
          yarn eslint packages/manifest-helper
      - name: Test
        run: |
          yarn workspace @storyblok/field-plugin test
          yarn workspace @storyblok/manifest-helper test
      - name: Build
        run: yarn workspace @storyblok/field-plugin build
