on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# https://github.com/amannn/action-semantic-pull-request
jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            common
            lib
            sandbox
            cli
            template
            demo
            helper
            deps
          requireScope: true
